"""
Django settings for Dexbook project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s*@5zy0q6@i2pyjozjl_m2jer5#endyr7lxljzjuk0%so_8=-3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework'
    "users",
    "auth_2fa",
    "books",
    "progress",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Dexbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dexbook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

# settings.py

# Меняем UTC на Ташкент
TIME_ZONE = 'Asia/Tashkent'

# Убедись, что эта настройка тоже равна True (она позволяет Django корректно работать с датами в БД)
USE_TZ = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

# Делаем медиа общим для ВСЕГО проекта
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'


# EMAIL_BACKEND — это наш главный рубильник. Вместо консольного бэкенда мы включаем smtp.EmailBackend. Мы говорим Django: «Всё, тесты в терминале кончились. Теперь бери данные и отправляй их в сеть через протокол SMTP».
#
# EMAIL_HOST — это сетевой адрес (домен) сервера, к которому Django должен подключиться. У каждого почтового сервиса он свой. У Google это smtp.gmail.com. Это как адрес дома, куда наш бэкенд будет стучаться.
#
# EMAIL_PORT — номер «двери» (порта) на сервере Google, через которую нас впустят. Для защищенного соединения обычно используется порт 587.
#
# EMAIL_USE_TLS — это флаг безопасности (принимает True или False). TLS (Transport Layer Security) — это протокол шифрования. Если он включен (True), то все данные (включая твой пароль от почты и текст писем) будут шифроваться перед отправкой в интернет, чтобы их никто не смог перехватить по пути.
#
# EMAIL_HOST_USER — твой реальный логин (email) от почты Gmail, с которой будут уходить письма (например, твоя_почта@gmail.com).
#
# EMAIL_HOST_PASSWORD — самый важный и деликатный момент. Сюда нельзя вводить твой обычный пароль от почты, с которым ты заходишь в аккаунт! Google заблокирует такую попытку ради безопасности. Сюда нужно будет вставить специальный Пароль приложения (App Password) — это 16-значный код, который генерируется в настройках аккаунта Google специально для сторонних программ вроде твоего Django.


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mrbomba752@gmail.com'
EMAIL_HOST_PASSWORD = 'lsnr cjdu zvjc hfhl'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
